### ISSUE TITLE
A way to mark if it's an alone or everyone ghost

### ISSUE THREAD

**Issue by letiv** [zuffdaddy/phasmohelper#12]
always end up forgetting and asking right when i leave the van

**Comment by WhiskeeDev** [comment]
This is what the "shy ghost" button is for, if it's "shy" it's an alone ghost.
Otherwise it's an everyone.

**Comment by letiv** [comment]
ohh. not sure that really came across until now since i thought that was just to mark it's behavior. thanks 👍
