### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hejsherz** [zuffdaddy/phasmohelper#13]
Make a rule out system for ruling out evidences, like a slider bar with these to rule out or just a simple right click on the evidence to make it rule out or something. Something like this system has https://lemon-field-0b94c1010.azurestaticapps.net/, will help quite a bit ruling out evidences to see what the correct ghost can be and if you rule out let's say fingerprints it removes all ghosts with fingerprints in their evidence

**Comment by zuffdaddy** [comment]
Added with a06bc689f7c4325908bb8f5b4302d846203a7763

**Comment by hejsherz** [comment]
Thank you a lot, it's appreciated @Zuffdaddy
