### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ZXbatata123** [zuffdaddy/phasmohelper#15]
all functions appear to don't be working or almost all, idk if is just for me

**Comment by zuffdaddy** [comment]
Do you have javascript enabled for your browser? It's working fine on my end

**Comment by ZXbatata123** [comment]
I'll see it later but I think I have it enabled

Em seg, 23 de nov de 2020 3:49 PM, zuffdaddy <notifications@github.com>
escreveu:
