### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by coolced101** [zuffdaddy/phasmohelper#16]
hey i would love to see another page with just pure info on every ghost
i mean like most info then just when you turn on ghost info and just look at the basic info
im talking about a full seperate page on the website with every ghost and very advanced info about them with like there  most common behavior and the way they act and react to certains things..

this is just a suggestion. i think its a very good suggestion but its ur website but yeah man nice website it helps alot thx bye..

**Comment by zuffdaddy** [comment]
I'll consider this for a future project but right now it's not in the scope of this one.
