### ISSUE TITLE
Suggestion / Feature addition

### ISSUE THREAD

**Issue by TheInfamousBug** [zuffdaddy/phasmohelper#17]
A suggestion that would be twofold would be for the ability to specifically negate a type of evidence or an entire ghost by clicking on an evidence piece on a ghost itself to negate it. Or perhaps make it a double click to "Ignore" or similar. As a challenge hunter occasionally, I do "no evidence" challenges, and when you don't see freezing breath after a time, you know it is ruled out. Similarly, if a Ghost doesn't travel at the speed of light at you during a hunt, you can rule out Jinn or Revenant instantly. Clicking on a ghost's nameplate could be added as a "soft removal" from the pool. Similarly, either double clicking an evidence, or having it as a little X button to the side of it to remove it from the pool would be wonderful to have.

**Comment by Harjas2102** [comment]
I logged on here to suggest the exact same thing and am very happy to see this. I would love for us to "Cross Out" abilities that we know can't be it, given our use of the process of elimination.

**Comment by zuffdaddy** [comment]
Fixed with a06bc689f7c4325908bb8f5b4302d846203a7763
