### ISSUE TITLE
Negative Evidence

### ISSUE THREAD

**Issue by alexanderghenry** [zuffdaddy/phasmohelper#19]
I wish I could say "there are no freezing temps" or "there are no orbs" and eliminate all those ghosts.  Maybe make that a right-click or second click on the existing buttons, and use the crossout on the words?

**Comment by nornaro** [comment]
The reason I use other site is that this is missing here.

**Comment by alexanderghenry** [comment]
> 
> 
> The reason I use other site is that this is missing here.

Which other site do you use?

**Comment by Klypsy** [comment]
> 
> 
> > The reason I use other site is that this is missing here.
> 
> Which other site do you use?

can i also have link for site? i like this phasmo site but im sure i will need the negative evidence web sometimes too, this site will still be my main :3

**Comment by zuffdaddy** [comment]
Fixed with a06bc689f7c4325908bb8f5b4302d846203a7763
