### ISSUE TITLE
Bring Back Water Objective

### ISSUE THREAD

**Issue by Prestad** [zuffdaddy/phasmohelper#20]
I know that the objective has been dropped from Beta, but it's still relevant in the stable live version for now. I like to stream the game, and I use this site to show the info, so it would be nice to have this site be current with the live stable version. Of course, once the stable version gets rid of it, then drop it at that time, but it should be there for now still.

**Comment by Mondanzo** [comment]
Maybe add the possibility to choose between branch as well? Having both versions available and the phasmo.site being the stable one and phasmo.site/beta being the unstable sounds like a very handy thing, especially cuz so there won't be much effort to update once the stable branch adapts all the beta changes.

**Comment by zuffdaddy** [comment]
For now I'll just keep one branch. If significant changes come in a future beta patch I may have two.
