### ISSUE TITLE
Missing "Have a member of your team escape the Ghost during a hunt" objective

### ISSUE THREAD

**Issue by rorrell** [zuffdaddy/phasmohelper#24]
I don't see an objective that corresponds to the above.  Please add.  Thanks!

**Comment by zuffdaddy** [comment]
It is currently labeled as "Escape" but I'll change it to "Member Escape" to be more clear!

**Comment by rorrell** [comment]
Thanks!

**Comment by zuffdaddy** [comment]
Fixed with 4b760f6ab78378ea6d8d367002ced276d5ed02b4
