### ISSUE TITLE
Phasmo Helper

### ISSUE THREAD

**Issue by MadameGiGi** [zuffdaddy/phasmohelper#25]
Hi, I have a suggestion about the phasmo helper. If it is possible could you add to the web the Spanish language? 
Thank you very much.

**Comment by zuffdaddy** [comment]
I'll see what I can do to automate the process, in the meantime you can use this link: 
https://translate.google.com/translate?hl=&sl=en&tl=es&u=https%3A%2F%2Fphasmo.site%2F

**Comment by MadameGiGi** [comment]
Thank you very much
