### ISSUE TITLE
Add a license to this repo

### ISSUE THREAD

**Issue by loganripplinger** [zuffdaddy/phasmohelper#44]
Please [add a license to this repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) so that the open source community can know what they are and aren't allowed to do with the code.

As-is this repo does not have a license which means it has "No License" which is described as:

> "When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you." - https://choosealicense.com/no-permission/

If your intention _is_ to have "No License" then:

> You may, however, wish to add a copyright notice and statement that you are not offering any license in a prominent place (e.g., your project’s README) so that users don’t assume you made an oversight. - https://choosealicense.com/no-permission/

Thank you :)

**Comment by zuffdaddy** [comment]
Done! Added MIT license. First time adding any license so if I did something wrong please let me know.

Thanks!
