### ISSUE TITLE
If there is only one possible remaining evidence, it does not appear

### ISSUE THREAD

**Issue by edlebert** [zuffdaddy/phasmohelper#6]
Check Ghost Orb and Finger Prints. There is only one possible piece of evidence left: Spirit Box. But it is hidden.

**Comment by zuffdaddy** [comment]
There is only one ghost possible with those 2 evidence. It wasn't even coded for that reason, when I added code for https://github.com/zuffdaddy/phasmohelper/commit/52fef61ccdc58ed1b935c6f3f000b4926fb3c353 it unintentionally fixed this issue: https://github.com/zuffdaddy/phasmohelper/issues/5
