### ISSUE TITLE
Incorrect Yokai Early Hunt Percentage

### ISSUE THREAD

**Issue by RoadsideDown** [zuffdaddy/phasmohelper#67]
The Yokai is currently listed as increasing from 50% to 90% for early hunt, 90% is incorrect, the correct position is 80%.

**Comment by zuffdaddy** [comment]
Thanks, fixed in [2d23f4b](https://github.com/zuffdaddy/phasmohelper/commit/2d23f4b1b3412e289310f94523d27a264b520937)
